import { PredefinedBreakReason, StopReasonOption, Subject, AppItem, AndroidPermission, UserSettings } from '../types';

export const PREDEFINED_BREAKS: PredefinedBreakReason[] = [
  {
    id: 'water',
    name: 'Drink Water',
    icon: '💧',
    durationMinutes: 2,
    description: 'Quick hydration break (2 mins -> +4m penalty)',
  },
  {
    id: 'pee',
    name: 'Pee',
    icon: '🚽',
    durationMinutes: 2,
    description: 'Restroom trip (2 mins -> +4m penalty)',
  },
  {
    id: 'poop',
    name: 'Poop',
    icon: '💩',
    durationMinutes: 10,
    description: 'Extended bathroom break (10 mins -> +20m penalty)',
  },
  {
    id: 'eat',
    name: 'Eat / Meal',
    icon: '🍽️',
    durationMinutes: 15,
    description: 'Quick meal or snack (15 mins -> +30m penalty)',
  },
  {
    id: 'rest',
    name: 'Short Rest / Stretch',
    icon: '🧘',
    durationMinutes: 5,
    description: 'Eyes rest & back stretch (5 mins -> +10m penalty)',
  },
  {
    id: 'tea_coffee',
    name: 'Tea / Coffee Refill',
    icon: '☕',
    durationMinutes: 4,
    description: 'Brew energy booster (4 mins -> +8m penalty)',
  },
];

export const STOP_REASONS: StopReasonOption[] = [
  { id: 'going_somewhere', label: 'Going somewhere', icon: '🏠' },
  { id: 'meal', label: 'Meal / Dinner time', icon: '🍽️' },
  { id: 'sleep', label: 'Sleep / Bedtime', icon: '😴' },
  { id: 'college_class', label: 'College / Class session', icon: '🎓' },
  { id: 'work', label: 'Work shift / Meeting', icon: '💼' },
  { id: 'important_reason', label: 'Important family / Emergency', icon: '🏥' },
  { id: 'battery_issue', label: 'Phone / Battery issue', icon: '🔋' },
  { id: 'other', label: 'Other custom reason', icon: '📝', requiresDetails: true },
];

export const DEFAULT_SUBJECTS: Subject[] = [
  { id: 'math', name: 'Mathematics', color: '#3B82F6', icon: 'Sigma', createdAt: Date.now() - 86400000 * 30 },
  { id: 'physics', name: 'Physics', color: '#8B5CF6', icon: 'Atom', createdAt: Date.now() - 86400000 * 30 },
  { id: 'cnc', name: 'CNC', color: '#10B981', icon: 'Cpu', createdAt: Date.now() - 86400000 * 25 },
  { id: 'manufacturing', name: 'Manufacturing', color: '#F59E0B', icon: 'Cog', createdAt: Date.now() - 86400000 * 20 },
  { id: 'english', name: 'English', color: '#EC4899', icon: 'BookOpen', createdAt: Date.now() - 86400000 * 15 },
];

export const DEFAULT_APPS: AppItem[] = [
  {
    id: 'google',
    name: 'Google Search & Docs',
    packageName: 'com.google.android.googlequicksearchbox',
    category: 'reference',
    iconName: 'Search',
    isAllowed: true,
    isDefault: true,
    launchUrl: 'https://www.google.com',
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    packageName: 'com.openai.chatgpt',
    category: 'productivity',
    iconName: 'Bot',
    isAllowed: true,
    isDefault: true,
    launchUrl: 'https://chatgpt.com',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp (Study Groups)',
    packageName: 'com.whatsapp',
    category: 'communication',
    iconName: 'MessageCircle',
    isAllowed: true,
    isDefault: true,
    launchUrl: 'https://web.whatsapp.com',
  },
  {
    id: 'calculator_builtin',
    name: 'Study Calculator',
    packageName: 'com.studymode.calculator',
    category: 'productivity',
    iconName: 'Calculator',
    isAllowed: true,
    isDefault: true,
  },
  {
    id: 'quick_notes',
    name: 'Quick Notes',
    packageName: 'com.studymode.notes',
    category: 'productivity',
    iconName: 'FileText',
    isAllowed: true,
    isDefault: true,
  },
  // Blocked applications
  {
    id: 'instagram',
    name: 'Instagram',
    packageName: 'com.instagram.android',
    category: 'social',
    iconName: 'Camera',
    isAllowed: false,
    isDefault: false,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    packageName: 'com.google.android.youtube',
    category: 'entertainment',
    iconName: 'Video',
    isAllowed: false,
    isDefault: false,
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    packageName: 'com.zhiliaoapp.musically',
    category: 'social',
    iconName: 'Share2',
    isAllowed: false,
    isDefault: false,
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    packageName: 'com.twitter.android',
    category: 'social',
    iconName: 'Send',
    isAllowed: false,
    isDefault: false,
  },
  {
    id: 'gaming_app',
    name: 'Mobile Games',
    packageName: 'com.mobile.game.launcher',
    category: 'games',
    iconName: 'Gamepad2',
    isAllowed: false,
    isDefault: false,
  },
  {
    id: 'reddit',
    name: 'Reddit',
    packageName: 'com.reddit.frontpage',
    category: 'social',
    iconName: 'Globe',
    isAllowed: false,
    isDefault: false,
  },
  {
    id: 'netflix',
    name: 'Netflix',
    packageName: 'com.netflix.mediaclient',
    category: 'entertainment',
    iconName: 'Tv',
    isAllowed: false,
    isDefault: false,
  },
];

export const ANDROID_PERMISSIONS: AndroidPermission[] = [
  {
    id: 'usage_stats',
    name: 'Usage Access (App Detection)',
    code: 'android.permission.PACKAGE_USAGE_STATS',
    description: 'Allows Study Mode to detect when a distracting app is launched during active study.',
    whyNeeded: 'Strictly required to detect and prevent access to blocked apps while in Timeskip Mode.',
    granted: true,
    iconName: 'Activity',
    badge: 'Required',
  },
  {
    id: 'accessibility',
    name: 'Accessibility Service (App Blocker)',
    code: 'android.permission.BIND_ACCESSIBILITY_SERVICE',
    description: 'Instantly redirects screen back to Study Mode when blocked applications are tapped.',
    whyNeeded: 'Required for real-time foreground window detection and blocking overlay display.',
    granted: true,
    iconName: 'ShieldAlert',
    badge: 'Required',
  },
  {
    id: 'notifications',
    name: 'Post Notifications',
    code: 'android.permission.POST_NOTIFICATIONS',
    description: 'Delivers 60-min cycle completion chimes, 5-min warning alerts, and 10-min urgent return alarms.',
    whyNeeded: 'Essential for keeping you informed when phone is locked or screen is off.',
    granted: true,
    iconName: 'Bell',
    badge: 'Required',
  },
  {
    id: 'system_alert',
    name: 'Display Over Other Apps',
    code: 'android.permission.SYSTEM_ALERT_WINDOW',
    description: 'Presents the Timeskip Mode locked screen over blocked apps if an unauthorized launch occurs.',
    whyNeeded: 'Ensures immediate deterrence and shows remaining study cycle penalty.',
    granted: true,
    iconName: 'Layers',
    badge: 'Required',
  },
  {
    id: 'battery_optimization',
    name: 'Ignore Battery Optimizations',
    code: 'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS',
    description: 'Prevents Android OS from killing the background study countdown timer during long sessions.',
    whyNeeded: 'Guarantees reliable background timing and unbroken session integrity.',
    granted: true,
    iconName: 'Zap',
    badge: 'Recommended',
  },
];

export const ALARM_RINGTONES_OPTIONS = [
  { id: 'chime', label: 'Classic Marimba Chime', description: 'Gentle 4-tone ascending melodic chime' },
  { id: 'zen_bowl', label: 'Zen Tibetan Singing Bowl', description: 'Harmonic resonant acoustic chime for calm focus' },
  { id: 'digital_beep', label: 'Digital Watch Beep', description: 'Crisp, modern double-beep alert' },
  { id: 'radar', label: 'Radar Sonar Pulse', description: 'Echoing submarine sonar pulse' },
  { id: 'bell', label: 'Temple Meditation Bell', description: 'Long sustained golden bell strike' },
  { id: 'marimba', label: 'Energetic Morning Marimba', description: 'Lively ascending melodic arpeggio' },
  { id: 'siren', label: 'High Urgency Alarm', description: 'Fast attention-grabbing pulsing alert' },
  { id: 'custom', label: 'Custom Uploaded Ringtone', description: 'Custom MP3 / WAV audio uploaded from device' },
] as const;

export const DEFAULT_SETTINGS: UserSettings = {
  dailyGoalHours: 6,
  studyCycleMinutes: 60,
  breakPenaltyMultiplier: 2,
  warning5MinEnabled: true,
  alarm10MinEnabled: true,
  soundEnabled: true,
  alarmVolume: 0.8,
  cycleCompleteRingtone: 'chime',
  warningRingtone: 'digital_beep',
  urgentRingtone: 'siren',
  customAlarmAudioUrl: null,
  customAlarmFileName: null,
  wakeLockEnabled: true,
  keepScreenAlwaysOn: true,
  theme: 'dark',
  accentColor: 'amber',
  onboardingCompleted: true,
};

export const DEFAULT_TODOS: import('../types').TodoItem[] = [
  {
    id: 'todo-1',
    title: 'Solve 10 Differential Equations practice problems',
    subjectId: 'math',
    subjectName: 'Mathematics',
    priority: 'high',
    estimatedMinutes: 60,
    completed: false,
    createdAt: Date.now() - 3600000 * 3,
  },
  {
    id: 'todo-2',
    title: 'Review CNC M-Code subroutines and canned cycles',
    subjectId: 'cnc',
    subjectName: 'CNC',
    priority: 'medium',
    estimatedMinutes: 45,
    completed: false,
    createdAt: Date.now() - 3600000 * 2,
  },
  {
    id: 'todo-3',
    title: 'Read Chapter 4 Thermodynamics notes',
    subjectId: 'physics',
    subjectName: 'Physics',
    priority: 'low',
    estimatedMinutes: 30,
    completed: true,
    createdAt: Date.now() - 3600000 * 5,
    completedAt: Date.now() - 3600000 * 1,
  },
];

export const DEFAULT_TARGET_TOPICS: import('../types').TargetTopic[] = [
  {
    id: 'topic-1',
    title: 'Integration by Parts & Trigonometric Substitution',
    subjectId: 'math',
    subjectName: 'Mathematics',
    status: 'in_progress',
    targetCycles: 2,
    notes: 'Focus on reduction formulas and definite integral boundaries.',
    subCheckpoints: [
      { id: 'sub-1', label: 'Formula derivation ∫u dv = uv - ∫v du', done: true },
      { id: 'sub-2', label: 'LIATE rule prioritization exercises', done: true },
      { id: 'sub-3', label: 'Euler identity substitutions', done: false },
    ],
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'topic-2',
    title: 'CNC G02 / G03 Circular Interpolation & Cutter Compensation',
    subjectId: 'cnc',
    subjectName: 'CNC',
    status: 'not_started',
    targetCycles: 1,
    notes: 'Understand G41 (left) and G42 (right) cutter radius offsets.',
    subCheckpoints: [
      { id: 'sub-4', label: 'I, J, K incremental center coordinates', done: false },
      { id: 'sub-5', label: 'Lead-in and lead-out arc programming', done: false },
    ],
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'topic-3',
    title: 'Laws of Thermodynamics & Carnot Engine Efficiency',
    subjectId: 'physics',
    subjectName: 'Physics',
    status: 'completed',
    targetCycles: 1,
    notes: 'η = 1 - (Tc / Th). Maximum theoretical efficiency limits.',
    subCheckpoints: [
      { id: 'sub-6', label: 'First law: ΔU = Q - W', done: true },
      { id: 'sub-7', label: 'Second law & entropy calculations', done: true },
    ],
    createdAt: Date.now() - 86400000 * 2,
  },
];

export const DEFAULT_FLASHCARDS: import('../types').FlashCard[] = [
  {
    id: 'fc-1',
    front: 'Integrating Factor for 1st Order Linear DE (dy/dx + P(x)y = Q(x))',
    back: 'IF = e^(∫ P(x) dx)\nGeneral solution: y · IF = ∫ (Q(x) · IF) dx + C',
    subjectId: 'math',
    subjectName: 'Mathematics',
    mastered: true,
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'fc-2',
    front: 'What is the purpose of G43 in CNC Machining?',
    back: 'Tool Length Compensation (+Z direction). Activated with H-word offset register (e.g., G43 H01 Z1.0).',
    subjectId: 'cnc',
    subjectName: 'CNC',
    mastered: false,
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'fc-3',
    front: 'Carnot Heat Engine Maximum Theoretical Efficiency (η)',
    back: 'η = 1 - (T_cold / T_hot)\nNote: Temperatures MUST be expressed in Kelvin (K).',
    subjectId: 'physics',
    subjectName: 'Physics',
    mastered: false,
    createdAt: Date.now() - 86400000 * 2,
  },
];

